### ISSUE TITLE
deleted are shown

### ISSUE THREAD

**Issue by pseudom** [madec-project/ezvis#41]

**Comment by parmentf** [comment]
It's possible that we forgot to filter with a selector hiding a `deleted`-state document.

But where?
Please precise the page where it is visible.

**Comment by parmentf** [comment]
OK, after discussing with IRL, I know that it was a whole file removed from the data repository which content was still visible in ezVIS.

I think that was likely a problem of mixing between old and new data in mongo "cache" collections.
Linked to #50.
