### ISSUE TITLE
Corpus fields for dates are limited by general itemsPerPage setting

### ISSUE THREAD

**Issue by MuseGlobal** [madec-project/ezvis#93]
We setup ezVIS for visualizing ezPAARSE CSVs and noticed that the corpus fields are limited by the itemsPerPage setting. More exactly the "period" widget from the Dashboard is limiting the size of the dates array to the value set in itemsPerPage . For example we had itemsPerPage=50, this made the period widget from the dashboard to remain stuck at 20170219 (31 days in January + 19 days = 50). Or is there a property for the corpus field to ignore the itemsPerPage value ? Or specify for that corpus field an itemsPerPage that will override the global one? Thanks

**Comment by parmentf** [comment]
I think the data loading is not finished yet, and you visualize only a part of the data.

Normally, `corpusFields` are not limited by `itemsPerPage`, but depends on the already loaded data (you can see the dashboard before all data is loaded).

Could you reload the page, after a while?

**Comment by MuseGlobal** [comment]
I triad many refreshes, but it does not work, the data finishes loading and it is not partial data. From the config, at the request:
 /compute.json?operator=distinct&field=dateSansTiret
comes the JSON, and in the array ".data ._id" I only get the first 50 values. I also tested with other values for itemsPerPage and each time the size of the array adjusted correspondingly to match it.

**Comment by parmentf** [comment]
Oh. Strange that we did not spot it sooner.

You're right.

I suggest you modify the `corpusFields`'s request, from `/compute.json?operator=distinct&field=dateSansTiret` to `/compute.json?operator=distinct&field=dateSansTiret&itemsPerPage=`, by adding `&itemsPerPage=` at the end of the request.

If you prefer, you can add a `0`, to get `&itemsPerPage=0`.

This parameter overrides the configuration.

Tell if it works for you.

**Comment by MuseGlobal** [comment]
It seems it is working now. Thanks.
