### ISSUE TITLE
Use proper icon depending on the graph type

### ISSUE THREAD

**Issue by gmella** [madec-project/ezvis#99]
This would be a nice improvement to change the icon in the left menu depending on the chart type.

By this way we could avoid to set long titles if we present the same data in different way.

Thanks,

**Comment by parmentf** [comment]
As long as we do not develop ezvis any more, but are including its feature into the [lodex](https://github.com/Inist-CNRS/lodex/) application, I think this is foreseen in lodex.

Lodex is a tool to publish data in semantic web's standard, but the current project is a convergence with ezVIS (the semantic part is not required).

**Comment by gmella** [comment]
Ok. I understand. Please may you put in the EzVis's Readme and project title that Iodex supersed this project.

Thank you for your answer. I will try to  look on swithing to Iodex if easy.
And thank you for the great packaging of your tools.

**Comment by kerphi** [comment]
Hello @gmella great to see ezvis is used! could you please tell us a bit more about your use case? why are  you using ezvis? which problems ezvis is solving for you?

**Comment by gmella** [comment]
Hi kerphi, 
We are build a corpus of publications that is associated to a grant in our observatory and show some indicators. Records are extraced from WOS using it's API. 
Ezvis is nice to provide a easy way for analysis.
Export also are interesting, even if CSV is not very reliable for data separated by ,

( ... and docker is good to test and integrate quickly on our side. )

Thx to your tools and team.

**Comment by gmella** [comment]
Another point...
Because I would like to use this tools to help collaborative validation of our corpus I will try to provide in the data table a Link to an external database which would identify false positive or confirmations.
One other nice function would be to get a way to add new record in the mongo-db. I did not remember anything related to such aspect in the documentation, but this should probably be possible to manage something so.

**Comment by parmentf** [comment]
ezVIS allows to add data, through putting a new file (with the same structure) in the data directory.
The directory is watched, and data should be loaded within few minutes.

Otherwise, in lodex there is an interface dedicated to:
- contribute when you're not the administrator
- add a notice/object/resource when you're logged in as an administrator.
